# Generated by Django 4.0.4 on 2022-05-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.TextField()),
                ('name', models.TextField()),
                ('skills', models.TextField(default='Skills')),
            ],
        ),
    ]
