# Generated by Django 4.0.4 on 2022-05-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_alter_applicant_id_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.IntegerField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='skills',
        ),
        migrations.AddField(
            model_name='applicant',
            name='cover_letter',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='applicant',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='applicant',
            name='job_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='applicant',
            name='website',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='id_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
