# Generated by Django 4.0.4 on 2022-05-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_job_remove_applicant_skills_applicant_cover_letter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='id_no',
            field=models.IntegerField(),
        ),
    ]
