# Generated by Django 4.0.4 on 2022-05-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0004_alter_applicant_id_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='id_no',
            field=models.IntegerField(default=0),
        ),
    ]
