# Generated by Django 4.0.4 on 2022-05-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('email', models.TextField(default='')),
                ('website', models.TextField(default='')),
                ('cover_letter', models.TextField(default='')),
                ('job_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('applicant_id', models.IntegerField()),
            ],
        ),
    ]
